COPY mapaUFV."E_PROPOSTA" ("ID_PROPOSTA", "CD_PROPOSTA_SICONV", "SG_UF_PROPONENTE", "NM_MUNICIPIO_PROPONENTE", "CD_MUNICIPIO_IBGE", "CD_ORGAO_SUPERIOR", "NM_ORGAO_SUP_DO_CONCEDENTE", "CS_NATUREZA_JURIDICA", "NR_PROPOSTA", "DD_PROPOSTA", "ME_PROPOSTA", "AN_PROPOSTA", "DT_PROPOSTA", "CD_ORGAO", "NM_ORGAO_CEDENTE", "CS_MODALIDADE_PROPOSTA", "NR_CNPJ_PROPONENTE", "NM_PROPONENTE", "CD_CEP_PROPONENTE", "ED_PROPONENTE", "NM_BAIRRO_PROPONENTE", "NM_BANCO", "CS_SITUACAO_CONTA", "CS_SITUACAO_PROJETO_BASICO", "CS_SITUACAO_PROPOSTA", "DT_INICIO_VIGENCIA", "DT_FIM_VIGENCIA", "DS_OBJETO_PROPOSTA", "NM_ITEM_INVESTIMENTO", "ST_ENVIADA_MANDATARIA", "NM_SUBTIPO_PROPOSTA", "DS_SUBTIPO_PROPOSTA", "VL_GLOBAL_PROPOSTA", "VL_REPASSE_PROPOSTA", "VL_CONTRAPARTIDA_PROPOSTA", "NM_UNIDADE_RESPONSAVEL", "CD_VINCULACAO", "DS_REPASSE", "NM_AUTOR", "NR_PROCESSO", "CS_EMPENHADO", "CS_SITUACAO_PUBLICACAO", "CS_CATEGORIA", "CD_REPASSE")
FROM 'output\proposta.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_CONVENIO" ("ID_CONVENIO", "NR_CONVENIO", "CD_PROPOSTA_SICONV", "DT_ASSINATURA_CONVENIO", "CS_STATUS_CONVENIO", "CS_SUBSITUACAO_CONVENIO", "CS_STATUS_PUBLICACAO_CONVENIO", "ST_INSTRUMENTO_ATIVO", "ST_OPERA_COM_OBTV", "NR_PROCESSO", "NR_UG_EMITENTE", "DT_PUBLICACAO_CONVENIO", "DT_INICIO_VIGENCIA", "DT_FIM_VIGENCIA", "DT_FIM_VIGENCIA_ORIGINAL", "PZ_PRESTACAO_CONTAS", "DT_LIMITE_PRESTACAO_CONTAS", "DT_CLAUSULA_SUSPENSIVA", "DT_RETIRADA_CLAUSULA_SUSPENSIVA", "QT_DIAS_CLAUSULA_SUSPENSIVA", "CS_STATUS_CONTRATACAO_CONVENIO", "ST_ASSINATURA_DO_CONVENIO", "DS_MOTIVO_SUSPENSAO", "ST_POSSUI_FOTO", "QT_CONVENIOS", "QT_TERMOS_ADITIVOS", "QT_PRORROGAS", "VL_GLOBAL_CONVENIO", "VL_REPASSE_CONVENIO", "VL_CONTRAPARTIDA_CONVENIO", "VL_EMPENHADO_CONVENIO", "VL_DESEMBOLSADO_CONVENIO", "VL_SALDO_REMAN_TESOURO", "VL_SALDO_REMAN_CONVENENTE", "VL_RENDIMENTO_APLICACAO", "VL_INGRESSO_CONTRAPARTIDA", "VL_SALDO_CONTA", "VL_GLOBAL_ORIGINAL_CONVENIO", "ID_PROPOSTA")
FROM 'output\convenio.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_PAGAMENTO" ("ID_PAGAMENTO", "NR_MOVIMENTACAO_FINANCEIRA", "NR_CONVENIO", "ID_FORNECEDOR", "NM_FORNECEDOR", "CS_MOVIMENTACAO_FINANCEIRA", "DT_PAGAMENTO", "NR_DOC_LIQUIDACAO", "CS_DOCUMENTO_LIQUIDACAO", "VL_PAGO")
FROM 'output\pagamento.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_META_CRONO_FISICO" ("ID_META_CRONO_FISICO", "CD_META_CRONO_FISICO_SICONV", "CD_PROPOSTA_SICONV", "NR_CONVENIO", "CD_PROGRAMA", "DS_PROGRAMA", "NR_META", "CS_META", "DS_META", "DT_INICIO_META", "DT_FIM_META", "SG_UF_META", "NM_MUNICIPIO_META", "ED_ENDERECO_META", "CD_CEP_META", "QT_META", "NM_UNIDADE_FORNECIMENTO_META", "VL_META", "ID_PROPOSTA", "ID_CONVENIO")
FROM 'output\meta_crono_fisico.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_AJUSTE_PT" ("ID_AJUSTE_PT", "NR_CONVENIO", "CD_CONVENIO_TRANSFEREGOV", "NR_AJUSTE_PT", "CS_SITUACAO_AJUSTE_PT", "NR_CPF_RESPONSAVEL_REGISTRO", "NM_RESPONSAVEL_REGISTRO", "DT_SOLICITACAO", "DS_OBJETO_ALTERACAO", "DS_JUSTIFICATIVA", "DS_MOTIVO_AJUSTE_PT", "ID_CONVENIO")
FROM 'output\ajustes_pt.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_CRONOGRAMA_DESEMBOLSO" ("ID_CRONOGRAMA_DESEMBOLSO", "CD_PROPOSTA_SICONV", "NR_CONVENIO", "NR_PARC_CRONOGRAMA_DESEMBOLSO", "ME_CRONOGRAMA_DESEMBOLSO", "AN_CRONOGRAMA_DESEMBOLSO", "CS_RESP_CRONOGRAMA_DESEMBOLSO", "VL_PARC_CRONOGRAMA_DESEMBOLSO", "ID_PROPOSTA", "ID_CONVENIO")
FROM 'output\cronograma_desembolso.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_DESBLOQUEIO_CR" ("ID_DESBLOQUEIO_CR", "NR_CONVENIO", "NR_ORDEM_BANCARIA", "DT_CADASTRO", "DT_ENVIO", "CS_RECURSO_DESBLOQUEIO", "VL_TOTAL_DESBLOQUEIO", "VL_DESBLOQUEADO", "VL_BLOQUEADO", "ID_CONVENIO")
FROM 'output\desbloqueio_cr.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_DESEMBOLSO" ("ID_DESEMBOLSO", "CD_DESEMBOLSO_SICONV", "NR_CONVENIO", "DT_ULTIMO_DESEMBOLSO", "QT_DIAS_SEM_DESEMBOLSO", "DT_DESEMBOLSO", "AN_DESEMBOLSO", "ME_DESEMBOLSO", "NR_SIAFI", "CD_UG_EMITENTE_DH", "DS_OBSERVACAO_DH", "VL_DESEMBOLSADO", "ID_CONVENIO")
FROM 'output\desembolso.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_EMENDA" ("ID_EMENDA", "CD_PROPOSTA_SICONV", "CS_QUALIF_PROPONENTE", "CD_PROGRAMA_EMENDA", "NR_EMENDA", "NM_PARLAMENTAR", "NR_CNPJ_BENEFICIARIO_EMENDA", "ST_IMPOSITIVO", "CS_TIPO_PARLAMENTAR", "VL_REPASSE_PROPOSTA_EMENDA", "VL_REPASSE_EMENDA")
FROM 'output\emenda.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_EMPENHO" ("ID_EMPENHO", "CD_EMPENHO_SICONV", "NR_CONVENIO", "NR_EMPENHO", "CD_TIPO_NOTA_EMPENHO", "CS_TIPO_NOTA", "DT_EMISSAO", "CD_SITUACAO_EMPENHO", "CS_SITUACAO_EMPENHO", "NR_UG_EMITENTE", "NM_UG_RESPONSAVEL", "CD_FONTE_RECURSO", "CD_NATUREZA_DESPESA", "CD_PLANO_INTERNO", "CD_PTRES", "VL_EMPENHADO", "ID_CONVENIO")
FROM 'output\empenho.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_EMPENHO_DESEMBOLSO" ("ID_EMPENHO_DESEMBOLSO", "CD_DESEMBOLSO_SICONV", "CD_EMPENHO_SICONV", "VL_GRUPO", "ID_EMPENHO", "ID_DESEMBOLSO")
FROM 'output\empenho_desembolso.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_ETAPA_CRONO_FISICO" ("ID_ETAPA_CRONO_FISICO", "CD_META_CRONO_FISICO_SICONV", "CD_ETAPA_CRONO_FISICO_SICONV", "NR_ETAPA", "DS_ETAPA", "DT_INICIO_ETAPA", "DT_FIM_ETAPA", "SG_UF_ETAPA", "NM_MUNICIPIO_ETAPA", "ED_ETAPA", "CD_CEP_ETAPA", "QT_ETAPA", "NM_UNID_FORNECIMENTO_ETAPA", "VL_ETAPA", "ID_META_CRONO_FISICO")
FROM 'output\etapa_crono_fisico.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_HISTORICO_SITUACAO" ("ID_HISTORICO_SITUACAO", "CD_PROPOSTA_SICONV", "NR_CONVENIO", "DH_HISTORICO_SITUACAO", "DS_HISTORICO_SITUACAO", "QT_DIAS_HISTORICO_SITUACAO", "CD_HISTORICO_SITUACAO", "ID_PROPOSTA", "ID_CONVENIO")
FROM 'output\historico_situacao.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_INGRESSO_CONTRAPARTIDA" ("ID_INGRESSO_CONTRAPARTIDA", "NR_CONVENIO", "DT_INGRESSO_CONTRAPARTIDA", "VL_INGRESSO_CONTRAPARTIDA", "ID_CONVENIO")
FROM 'output\ingresso_contrapartida.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_JUSTIFICATIVA_PROPOSTA" ("ID_JUSTIFICATIVA_PROPOSTA", "CD_PROPOSTA_SICONV", "DS_PUBLICO_ALVO", "DS_INTERESSES_RECIPROCOS", "DS_RESULTADOS_ESPERADOS", "DS_PROBLEMA_A_SER_RESOLVIDO", "DS_RELACAO_PROPOSTA_OBJETIVOS", "DS_CAPACIDADE_TECNICA", "DS_JUSTIFICATIVA", "ID_PROPOSTA")
FROM 'output\justificativas_proposta.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_LICITACAO" ("ID_LICITACAO", "CD_LICITACAO_SICONV", "NR_CONVENIO", "NR_LICITACAO", "CS_MODALIDADE_LICITACAO", "CS_PROCESSO_COMPRA", "CS_LICITACAO", "NR_PROCESSO_LICITACAO", "DT_PUBLICACAO_LICITACAO", "DT_ABERTURA_LICITACAO", "DT_ENCERRAMENTO_LICITACAO", "DT_HOMOLOGACAO_LICITACAO", "ST_STATUS_LICITACAO", "CS_SITUACAO_ACEITE_PROCESSO_EXEC", "NM_SISTEMA_ORIGEM", "DS_SITUACAO_SISTEMA", "VL_LICITACAO", "ID_CONVENIO")
FROM 'output\licitacao.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_OBTV_CONVENENTE" ("ID_OBTV_CONVENENTE", "NR_MOVIMENTACAO_FINANCEIRA", "ID_FAVORECIDO_OBTV_CONVENENTE", "NM_FAVORECIDO_OBTV_CONVENENTE", "DS_TIPO_AQUISICAO", "VL_PAGO_OBTV_CONVENENTE", "ID_PAGAMENTO")
FROM 'output\obtv_convenente.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_PLANO_APLICACAO" ("ID_PLANO_APLICACAO", "CD_PROPOSTA_SICONV", "SG_UF", "NM_MUNICIPIO", "CD_NATUREZA_AQUISICAO", "DS_DESCRICAO_ITEM", "CD_CEP_ITEM", "ED_ITEM", "CS_TIPO_DESPESA_ITEM", "DS_NATUREZA_DESPESA", "DS_SITUACAO_ITEM", "CD_NATUREZA_DESPESA", "QT_ITEM", "VL_UNITARIO_ITEM", "VL_TOTAL_ITEM", "CD_ITEM_PAD_SICONV", "ID_PROPOSTA")
FROM 'output\plano_aplicacao.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_PAGAMENTO_TRIBUTO" ("ID_PAGAMENTO_TRIBUTO", "NR_CONVENIO", "DT_PAGAMENTO_TRIBUTO", "VL_PAGO_TRIBUTO")
FROM 'output\pagamento_tributo.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_PROPONENTE" ("ID_PROPONENTE", "CD_PROPONENTE_SICONV", "NR_CNPJ_PROPONENTE", "NM_PROPONENTE", "NM_MUNICIPIO_PROPONENTE", "SG_UF_PROPONENTE", "ED_PROPONENTE", "NM_BAIRRO_PROPONENTE", "CD_CEP_PROPONENTE", "ED_EMAIL_PROPONENTE", "NR_TEL_PROPONENTE", "NR_FAX_PROPONENTE")
FROM 'output\proponentes.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_PRORROGA_OFICIO" ("ID_PRORROGA_OFICIO", "NR_CONVENIO", "NR_PRORROGA", "DT_INICIO_PRORROGA", "DT_FIM_PRORROGA", "QT_DIAS_PRORROGACAO", "DT_ASSINATURA_PRORROGA", "ST_SITUACAO_PRORROGACAO", "ID_CONVENIO")
FROM 'output\prorroga_oficio.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_SOLICITACAO_ALTERACAO" ("ID_SOLICITACAO_ALTERACAO", "CD_SOLICITACAO_SICONV", "NR_CONVENIO", "NR_SOLICITACAO", "CS_SITUACAO_SOLICITACAO", "DS_OBJETO_SOLICITACAO", "CD_CONVENIO_TRANSFEREGOV", "CD_SOLICITACAO_ALTERACAO_TA", "NR_CPF_RESPONSAVEL_REGISTRO", "NM_RESPONSAVEL_REGISTRO", "DT_SOLICITACAO", "DS_OBJETO_ALTERACAO", "DS_JUSTIFICATIVA", "ID_CONVENIO")
FROM 'output\solicitacao_alteracao.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_TERMO_ADITIVO" ("ID_TERMO_ADITIVO", "NR_CONVENIO", "CD_SOLICITACAO_SICONV", "NR_TERMO_ADITIVO", "CS_TERMO_ADITIVO", "VL_GLOBAL_TA", "VL_REPASSE_TA", "VL_CONTRAPARTIDA_TA", "DT_ASSINATURA_TA", "DT_INICIO_TA", "DT_FIM_TA", "DS_JUSTIFICATIVA_TERMO_ADITIVO", "CD_CONVENIO_TRANSFEREGOV", "DS_OBJETO_ALTERACAO", "CS_SITUACAO_TA", "NR_CPF_RESPONSAVEL_REGISTRO_TA", "NM_RESPONSAVEL_REGISTRO_TA", "CS_SITUACAO_ENVIO_SIAFI", "CD_RETORNO_SIAFI", "DT_ENVIO_SIAFI", "DT_PUBLICACAO_DOU", "CD_UG_PUBLICACAO", "DT_ENVIO_DOU", "ID_CONVENIO")
FROM 'output\termo_aditivo.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');

COPY mapaUFV."E_MUNICIPIO" ("ID_MUNICIPIO", "CD_UF", "NM_UF", "SG_UF", "CD_MUNICIPIO", "NM_MUNICIPIO", "CD_REGIAO_GEO_INTERMEDIARIA", "NM_REGIAO_GEO_INTERMEDIARIA", "CD_REGIAO_GEO_IMEDIATA","NM_REGIAO_GEO_IMEDIATA","CD_MESOREGIAO_GEOGRAFICA", "NM_MESOREGIAO_GEOGRAFICA", "CD_MICROREGIAO_GEOGRAFICA", "NM_MICROREGIAO_GEOGRAFICA", "NR_LATITUDE", "NR_LONGITUDE")
FROM 'output\municipio.csv'
WITH (FORMAT csv, DELIMITER ',', HEADER, ENCODING 'UTF8');